version = 5.6.0
archive_dir = /etc/letsencrypt/archive/cloudaziz.com
cert = /etc/letsencrypt/live/cloudaziz.com/cert.pem
privkey = /etc/letsencrypt/live/cloudaziz.com/privkey.pem
chain = /etc/letsencrypt/live/cloudaziz.com/chain.pem
fullchain = /etc/letsencrypt/live/cloudaziz.com/fullchain.pem
[renewalparams]
account = e8f14cb7a4e1f2565ed8ab510e9e4820
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
cloudaziz.com = /var/www/certbot
www.cloudaziz.com = /var/www/certbot
